# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-03 19:55
from __future__ import unicode_literals

import HNApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityText', models.TextField()),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorsToVerify', models.CharField(default='', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adminUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdmitEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('doctors', models.ManyToManyField(to='HNApp.DoctorModel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='/static/HNApp/imageentries')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitEntries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HNApp.AdmitEntry')),
                ('imageEntries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HNApp.ImageEntry')),
            ],
        ),
        migrations.CreateModel(
            name='NurseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors', models.ManyToManyField(to='HNApp.DoctorModel')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(default='ft\'inches"', max_length=10)),
                ('weight', models.CharField(default='0 lbs', max_length=10)),
                ('blood_type', models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('O-', 'O-'), ('O+', 'O+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('Unknown', 'Unknown')], max_length=7)),
                ('gender', models.CharField(choices=[('----', '----'), ('Male', 'Male'), ('Female', 'Female')], default='----', max_length=6)),
                ('isAdmitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.CharField(max_length=13, validators=[HNApp.models.validate_insurance])),
                ('street_Address', models.CharField(default='N/A', max_length=40)),
                ('city', models.CharField(default='N/A', max_length=20)),
                ('state', models.CharField(choices=[('N/A', 'N/A'), ('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], default='N/A', max_length=3)),
                ('zip_Code', models.CharField(default='N/A', max_length=5)),
                ('phone_Number', models.CharField(default='N/A', max_length=10)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('emergency_contact_name', models.CharField(default='N/A', max_length=50)),
                ('emergency_contact_email', models.CharField(default='N/A', max_length=50)),
                ('emergency_contact_phone_number', models.CharField(default='N/A', max_length=11)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HNApp.DoctorModel')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HNApp.HospitalModel')),
                ('medicalProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HNApp.PatientMedicalProfile')),
                ('medicalRecord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HNApp.MedicalRecord')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HNApp.PatientModel')),
            ],
        ),
        migrations.CreateModel(
            name='TestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('isHidden', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VitalsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('weight', models.CharField(max_length=8)),
                ('height', models.CharField(max_length=8)),
                ('temperature', models.CharField(max_length=8)),
                ('bloodPressure', models.CharField(max_length=8)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'Doctor'), ('N', 'Nurse')], max_length=8)),
                ('isVerified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workerUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nursemodel',
            name='worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HNApp.WorkerModel'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='testEntries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HNApp.TestEntry'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vitalsEntries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HNApp.VitalsEntry'),
        ),
        migrations.AddField(
            model_name='hospitalmodel',
            name='nurses',
            field=models.ManyToManyField(to='HNApp.NurseModel'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HNApp.WorkerModel'),
        ),
    ]
